spring.application.name=LocalLens
# for database connection
spring.datasource.url=jdbc:postgresql://db.mtokaddjliauakhkgdqb.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=fddWKVpjhSEU6NGc
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update    
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#for mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=smartplant777@gmail.com
spring.mail.password=qjjp dwlo irxy swzh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


supabase.url=https://mtokaddjliauakhkgdqb.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10b2thZGRqbGlhdWFraGtnZHFiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MzY1OTc0NSwiZXhwIjoyMDc5MjM1NzQ1fQ.kKU3VjJ7sVRP75hRp_O-OqK0PFjGaWsWVCqSd-LRq1M
supabase.bucket=test

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB




