spring.application.name=LocalLens
# for database connection
spring.datasource.url=URL
spring.datasource.username=UNAME
spring.datasource.password=SUPABASE_PASS
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


sendgrid.key=SENDGRID_KEY


supabase.url=SUPABASE_URL
supabase.key=SUPABASE_KEY
supabase.bucket=test

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
