spring.application.name=LocalLens
# for database connection
spring.datasource.url=supabase url 
spring.datasource.username=postgres
spring.datasource.password=Supabase password 
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update    
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#for mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=Your mail here 
spring.mail.password=Mail pass 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


supabase.url=supabase url 
supabase.key=your supabase anon key 
supabase.bucket=test

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB




